// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBoDomx2ENDxoikwYmuaPMcrj1eto4JG5k',
    appId: '1:561993345309:web:777160006a8e55194cd9f4',
    messagingSenderId: '561993345309',
    projectId: 'chat-project-82d66',
    authDomain: 'chat-project-82d66.firebaseapp.com',
    storageBucket: 'chat-project-82d66.appspot.com',
    measurementId: 'G-778D93Q0CV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA4R1Qp2dYwy3fHhJKn_LY88prLeJ4m9wU',
    appId: '1:561993345309:android:c53bf6ad2478eaf44cd9f4',
    messagingSenderId: '561993345309',
    projectId: 'chat-project-82d66',
    storageBucket: 'chat-project-82d66.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyADM-gDlO2jtuXjNlp3Ijm8Cry8P2c4mf0',
    appId: '1:561993345309:ios:1020a2d29153b7554cd9f4',
    messagingSenderId: '561993345309',
    projectId: 'chat-project-82d66',
    storageBucket: 'chat-project-82d66.appspot.com',
    iosClientId: '561993345309-54l69du6seosru8r96r7u38sascrmrbg.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyADM-gDlO2jtuXjNlp3Ijm8Cry8P2c4mf0',
    appId: '1:561993345309:ios:1020a2d29153b7554cd9f4',
    messagingSenderId: '561993345309',
    projectId: 'chat-project-82d66',
    storageBucket: 'chat-project-82d66.appspot.com',
    iosClientId: '561993345309-54l69du6seosru8r96r7u38sascrmrbg.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatProject',
  );
}
